### PR TITLE
Anti-adblock on nuvo.net

### PR DESCRIPTION
**Pull request by ryanbr**
Admiral anti-adblock makes this site unusable if you have sheilds on.

### CODE REVIEW

**Comment by snyderp** [comment]
@ryanbr I'm not seeing any anti-adblock messages on nuvo.net.  How can i trigger the anti-adblock, so I can check the anti-anti-adblock?

**Comment by ryanbr** [comment]
Ah correction, will only apply when cosmetic filtering is being applied. Admiral is a Anti-adblock service which will be the first thing people will see once cosmetic filtering is patched. see;

```
https://www.politicususa.com/
https://www.al.com/ 
https://www.pinknews.co.uk/
```

There is no damage deploying it earlier (just blocking their specific adserver domain), but can be delayed until cosmetic filtering is landed.

**Comment by snyderp** [comment]
I'll create a tag to keep track of these things (things that it makes sense to merge in once we do cosmetic filters)

**Comment by ryanbr** [comment]
ad domain no longer being used, closing this

**Pull request closed without merging**
