### PR TITLE
Update x13_cookies

### PR DESCRIPTION
**Pull request by ryanbr**
Counter the x13 cookies consent. Will remove if uBO takes this up

### CODE REVIEW

**Comment by mapx-** [comment]
`click-element` is visually not very nice

```
*##+js(trusted-click-element, button[data-action="choose"], , 500)
*##+js(trusted-click-element, button[data-action="choose"], , 500)
```

**Comment by mapx-** [comment]
`*##+js(trusted-click-element, button[data-action="accept-selected"], , 1000)`

**Comment by ryanbr** [comment]
A bit overeaching?

**Comment by mapx-** [comment]
sure, with all those domains added, otherwise why excessive ? The default seems to be always only about necessary cookies

**Comment by ryanbr** [comment]
Would also assume you accept all the trackers etc, rather than the minimum or necessary. Seems bad for privacy from accept all for everything.

**Pull request merged**
