### PR TITLE
Add more admiral servers

### PR DESCRIPTION
**Pull request by ryanbr**
Just a sync Admiral server list with Easyprivacy (ios) Just a followup from the previous pull req

https://github.com/brave/adblock-lists/pull/276

### CODE REVIEW

**Comment by snyderp** [comment]
@ryanbr maybe it'd be best to make a separate, iOS suplement list?  We can bundle that with the next iOS release, and that way other platforms don't get duplicate rules?  WDYT?

**Comment by ryanbr** [comment]
When we properly sync with Easyprivacy in slimlist, these rules could be removed.

**Comment by snyderp** [comment]
not necessarily, since its possible slimlist would not come across these domains during its random crawl.  So my thinking is that it'd be useful to both have a list of things that were always ship to iOS (and only iOS) regardless of SlimList, for this reason, but also maybe for web compat reasons too

**Comment by ryanbr** [comment]
Yeah, wouldn't be hard to move these rules into its own "admiral list" for slimlist.

**Comment by snyderp** [comment]
Sure, can you create that separate list?  And name it something more general, so that we can use it for other similar needs without the same naming problem we got into with `brave-unbreak`?  So something like `brave-ios`?

@jhreis whats the best way of getting this iOS filter list supplement integrated?

**Comment by ryanbr** [comment]
https://github.com/brave/adblock-lists/issues/279

**Comment by ryanbr** [comment]
PR was superseded by https://github.com/brave/adblock-lists/pull/326

**Pull request closed without merging**
