### PR TITLE
Remove exceptions for brave search

### PR DESCRIPTION
**Pull request by ryanbr**
PR to remove the exceptions for brave/brave-ios#7294

### CODE REVIEW

**Comment by pes10k** [comment]
Please do not merge thisOn May 14, 2023, at 20:41, Fanboynz ***@***.***> wrote:﻿PR to remove the exceptions for brave/brave-ios#7294



You can view, comment on, or merge this pull request online at:
  https://github.com/brave/adblock-lists/pull/1168

Commit Summary

  88132b1  Remove exceptions for brave search


File Changes  (1 file)

  
    M
    brave-unbreak.txt
    (8)
  


Patch Links:

  https://github.com/brave/adblock-lists/pull/1168.patch
  https://github.com/brave/adblock-lists/pull/1168.diff

**Comment by ryanbr** [comment]
Understood, wasn't going to be merged until I was given the okay

**Comment by iambrianfung** [comment]
i believe this can be closed by 
https://github.com/brave/adblock-lists/pull/1588

**Comment by ryanbr** [comment]
Yeah, no longer needed

**Pull request closed without merging**
