### PR TITLE
Block requests to localhost and similar, when not on localhost and similar

### LINKED ISSUE #462: Block connections to localhost resources from non localhost pages
We should block websites connecting to local resources (localhost, 127.0.0.1, etc) that are no local themselves

### PR DESCRIPTION
**Pull request by pes10k**
fixes #462

### CODE REVIEW

**Comment by llacb47** [comment]
add an anchor `||` ?

**Comment by ryanbr** [comment]
@antonok-edm uBO doesn't like ipv6, can adblock-rust work with ::1?

**Comment by llacb47** [comment]
change `~*.local` to `~local`. IDK if brave's adblock engine works differently but it works in uBo/abp

**Comment by pes10k** [comment]
thanks @llacb47 , like i mentioned to @ryanbr, glad to have you both helping me brute force this (you can probably tell i dont write non-trivial filter list rules often ;)

**Review by ryanbr — APPROVED** [review]
If `::1` is fine then this is okay.

**Review by antonok-edm — CHANGES_REQUESTED** [review]

**Comment by ryanbr** [comment]
I would also consider changing from .local^$.. to ||local^$...

**Comment by antonok-edm** [comment]
oh also, I don't think `~local` is working correctly - will continue to investigate

**Comment by pes10k** [comment]
okie dokie, will hold off on more changes until you report back :)

**Comment by pes10k** [comment]
okie as discussed, going to solve this by splitting into two PRs, this one w/o .local, and https://github.com/brave/adblock-lists/pull/465 which adds back in the .local addresses

**Review by antonok-edm — APPROVED** [review]

**Pull request merged**
