### PR TITLE
Adds rule to block ads from syntac.net

### PR DESCRIPTION
**Pull request by Jacalz**
Syntac.net is a site that serves as a container for ads on a couple websites and all there content is just total junk ads and stuff. They really have nothing aside from that.

An example of this would be that ads from syntac.net are shown on: https://domainhub.com/
Here is an example of the ads without the filter:
image
The red marking is not part of the ad...

### CODE REVIEW

**Comment by Jacalz** [comment]
@bbondy

**Comment by Jacalz** [comment]
I am tagging you @bbondy since you controll this repo 👍

**Comment by Jacalz** [comment]
Any news on merging this? @bbondy

**Comment by bbondy** [comment]
Thanks for the ping. Seems OK but forwarding to Luke to review and merge.

**Comment by Jacalz** [comment]
I think he basically has approved it already because I made the rule while talking to him and he told me to ping you 😜 But alright 👍

**Comment by bbondy** [comment]
No problem, best to tag him anyway since he's already aware for cases like that. Thanks!

**Comment by Jacalz** [comment]
Will close this, page seems to be empty...

**Pull request closed without merging**
