### PR TITLE
Fixes brave/brave-browser#9656

### PR DESCRIPTION
**Pull request by ryanbr**
This will fix issues regarding blocks on `mailchimp.com` caused by the Disconnect list. 

Fixing https://github.com/brave/brave-browser/issues/9656 on website: https://nocsok.com/about

`https://downloads.mailchimp.com/css/signup-forms/popup/2.0/banner.css`
`https://downloads.mailchimp.com/css/signup-forms/popup/2.0/layout-2.css`
`https://downloads.mailchimp.com/css/signup-forms/popup/2.0/modal.css`

Have requested removal of mailchimp from the Disconnect list.

### CODE REVIEW

**Comment by pes10k** [comment]
@ryanbr is it possible that there is also tracking code on mailchimp.com?  So that we can block tracking but not benign uses with a more narrow rule?

**Comment by ryanbr** [comment]
I haven't seen any trackers used by mailchimp previously, and nothing in Easyprivacy. Have checked a few mailchimp sites and its seems safe, I'm not sure why it's being blocked by the Disconnect list.

**Comment by ryanbr** [comment]
We did address the privacy issues regarding mailchimp in https://github.com/brave/adblock-lists/pull/359  (on a previous mailchimp issue)

**Comment by ryanbr** [comment]
Safe to merge @pes10k ?

**Comment by pes10k** [comment]
yep!  I'll merge now, thanks @ryanbr !

**Pull request merged**
