### PR TITLE
Sync With NoCoin List and nocoin-ublock

### PR DESCRIPTION
**Pull request by ryanbr**
1. Removed redundant custom filter `||load.jsecoin.com$third-party`  (redundant because of `||jsecoin.com^$third-party`)
2. Kept: `https://github.com/brave/adblock-lists/pull/32` `||greenindex.dynamic-dns.net/jqueryeasyui.js^$third-party`
3. Also properly import uBO no-coin snippets from https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/nocoin-ublock.txt

### CODE REVIEW

**Comment by ryanbr** [comment]
Given the size of the merge, If you're okay with this @pes10k  :)

**Comment by pes10k** [comment]
@ryanbr can you confirm that the new no-coin rules aren't redundant with https://github.com/brave/adblock-lists/blob/master/coin-miners.txt ?

**Comment by ryanbr** [comment]
This will actually update (all) the filters in https://github.com/brave/adblock-lists/blob/master/coin-miners.txt    Just checked via a redundancy on https://abpvn.com/ruleChecker/redundantRuleChecker.html  no redundant filters, some dubes in Easyprivacy at most. @pes10k

**Comment by pes10k** [comment]
Ah, then terrific, lets make it so :)

**Pull request merged**
