### PR TITLE
Fix https://github.com/brave/brave-browser/issues/19520

### PR DESCRIPTION
**Pull request by ryanbr**
Fixes https://github.com/brave/brave-browser/issues/19520

cc: @arthuredelstein

### CODE REVIEW

**Review by arthuredelstein — APPROVED** [review]

**Comment by pes10k** [comment]
@arthuredelstein just to check, will the new crawler catch this error case correctly?

**Comment by arthuredelstein** [comment]
In principle it would, yes, because this appears to be a timeout. However this subdomain would need to be on our list of domains.

Given that's not always the case, it does seem we should look into falling back if a site times out after an attempted upgrade. I opened a ticket to work on that: https://github.com/brave/brave-browser/issues/30267

**Comment by pes10k** [comment]
Great! Can you also add this as a possible fail state we can categorize in the study too?

**Comment by arthuredelstein** [comment]
> Great! Can you also add this as a possible fail state we can categorize in the study too?

Will do!

**Pull request merged**
