### PR TITLE
Add email subscriptions tracking

### PR DESCRIPTION
**Pull request by ryanbr**
From: https://github.com/AdguardTeam/AdguardFilters/blob/master/TrackParamFilter/sections/general_url.txt

**! https://github.com/AdguardTeam/AdguardFilters/issues/89869 ! email subscriptions tracking**
```
$removeparam=bsft_clkid
$removeparam=bsft_eid
$removeparam=bsft_mid
$removeparam=bsft_uid
$removeparam=bsft_aaid
$removeparam=bsft_ek
```

**! Matomo/Piwik** 
```
$removeparam=mtm_campaign
$removeparam=mtm_cid
$removeparam=mtm_content
$removeparam=mtm_group
$removeparam=mtm_keyword
$removeparam=mtm_medium
$removeparam=mtm_placement
$removeparam=mtm_source
$removeparam=pk_campaign
$removeparam=pk_medium
$removeparam=pk_source
```
**! Branch.io ( https://stackoverflow.com/questions/37882810/what-is-meaning-of-branch-match-id )**
`$removeparam=_branch_match_id`

**! Valuecommerce ( https://help.valuecommerce.ne.jp/mer/dl/ITP2.0_for_iTAG.pdf )**
`$removeparam=vc_lpp`

**! https://github.com/brave/brave-browser/issues/17507**
```
$removeparam=ml_subscriber
$removeparam=ml_subscriber_hash
```

### CODE REVIEW

**Comment by fmarier** [comment]
@ryanbr If you see any entries that come from Brave (`ml_subscriber` and `ml_subscriber_hash`), then they don't need to be added to the clean-url list since they'll be removed automatically earlier. 

They're not wrong, nor will they cause problems, they're just not necessary.

**Comment by pes10k** [comment]
just a thought, but you might want to leave them in the clean URL list (even if they're duplicates) is that we don't strip query parameters on same-site navigations, so there are at least possible cases where the query params are in the URL, but users still might want them removed.

**Comment by fmarier** [comment]
Good point. I don't think it's going to matter in this particular case since they're email newsletter trackers (therefore will be cross-site), but it may in other cases.

**Comment by fmarier** [comment]
PR to add the bsft ones to the main query filter: https://github.com/brave/brave-core/pull/15008

**Pull request merged**
