### PR TITLE
Fix youtube rules

### PR DESCRIPTION
**Pull request by Yuki2718**
Please test on iPad as I don't have, hope this doesn't cause occasional network error on videos. Another concern is it uses lookahead, do iOS scriptlets support this?

### CODE REVIEW

**Comment by Yuki2718** [comment]
Now detected

**Comment by ryanbr** [comment]
cc: @cuba

**Comment by Yuki2718** [comment]
> Another concern is it uses lookahead, do iOS scriptlets support this?

Actually the current rule already uses negative lookahead so I suppose it's okay.

**Comment by ryanbr** [comment]
okay, i guess so

**Pull request merged**
