### PR TITLE
Add sugarcoat rules list

### PR DESCRIPTION
**Pull request by ShivanKaul**
Related to https://github.com/brave/adblock-resources/pull/30

### CODE REVIEW

**Comment by ryanbr** [comment]
Should convert the `http` bits into `||` like the other rules. @ShivanKaul

**Comment by ryanbr** [comment]
Would this work still,

`||google-analytics.com/analytics.js$script,important,redirect=sugarcoat-analytics` in stead of `https://www.google-analytics.com/analytics.js$script,important,redirect=sugarcoat-analytics`



```
https://securepubads.g.doubleclick.net/gpt/pubads_impl_2021070101.js$script,important,redirect=sugarcoat-pubads_impl_2021070101
https://securepubads.g.doubleclick.net/gpt/pubads_impl_2021070701.js?31061757$script,important,redirect=sugarcoat-pubads_impl_2021070701
```
Seems to be a redundant, the top filter should already be covering it.

**Comment by ryanbr** [comment]
Just ran a redundancy check. Needs further cleanups:

```
https://assets.adobedtm.com/extensions/EPbde2f7ca14e540399dcc1f8208860b7b/AppMeasurement_Module_AudienceManagement.min.js$script,important,redirect=sugarcoat-AppMeasurement_Module_AudienceManagement.min has been made redundant by https://assets.adobedtm.com/extensions/EPbde2f7ca14e540399dcc1f8208860b7b/AppMeasurement_Module_AudienceManagement.min.js$script,important,redirect=sugarcoat-AppMeasurement_Module_AudienceManagement.min
https://bat.bing.com/bat.js$script,important,redirect=sugarcoat-bat has been made redundant by https://bat.bing.com/bat.js$script,important,redirect=sugarcoat-bat
https://www.google-analytics.com/analytics.js$script,important,redirect=sugarcoat-analytics has been made redundant by https://www.google-analytics.com/analytics.js$script,important,redirect=sugarcoat-analytics
https://securepubads.g.doubleclick.net/gpt/pubads_impl_2021072403.js$script,important,redirect=sugarcoat-pubads_impl_2021072403 has been made redundant by https://securepubads.g.doubleclick.net/gpt/pubads_impl_2021072403.js$script,important,redirect=sugarcoat-pubads_impl_2021072403
https://securepubads.g.doubleclick.net/tag/js/gpt.js$script,important,redirect=sugarcoat-gpt has been made redundant by https://securepubads.g.doubleclick.net/tag/js/gpt.js$script,important,redirect=sugarcoat-gpt
https://cd.connatix.com/connatix.player.js$script,important,redirect=sugarcoat-connatix.player has been made redundant by https://cd.connatix.com/connatix.player.js$script,important,redirect=sugarcoat-connatix.player
https://connect.facebook.net/en_US/fbevents.js$script,important,redirect=sugarcoat-fbevents has been made redundant by https://connect.facebook.net/en_US/fbevents.js$script,important,redirect=sugarcoat-fbevents
https://c.amazon-adsystem.com/aax2/apstag.js$script,important,redirect=sugarcoat-apstag has been made redundant by https://c.amazon-adsystem.com/aax2/apstag.js$script,important,redirect=sugarcoat-apstag
https://www.googletagservices.com/tag/js/gpt.js$script,important,redirect=sugarcoat-gpt has been made redundant by https://www.googletagservices.com/tag/js/gpt.js$script,important,redirect=sugarcoat-gpt
https://static.foxnews.com/static/isa/app/lib/VisitorAPI.js$script,important,redirect=sugarcoat-VisitorAPI has been made redundant by https://static.foxnews.com/static/isa/app/lib/VisitorAPI.js$script,important,redirect=sugarcoat-VisitorAPI
https://assets.adobedtm.com/71dcbb11123ce6b2e1ce4d47fd79a130aad3fc95/satelliteLib-177113f60f763788009998023cd15615fe2168a2.js$script,important,redirect=sugarcoat-satelliteLib-177113f60f763788009998023cd15615fe2168a2 has been made redundant by https://assets.adobedtm.com/71dcbb11123ce6b2e1ce4d47fd79a130aad3fc95/satelliteLib-177113f60f763788009998023cd15615fe2168a2.js$script,important,redirect=sugarcoat-satelliteLib-177113f60f763788009998023cd15615fe2168a2
https://cdn.quantummetric.com/qscripts/quantum-telegraph.js$script,important,redirect=sugarcoat-quantum-telegraph has been made redundant by https://cdn.quantummetric.com/qscripts/quantum-telegraph.js$script,important,redirect=sugarcoat-quantum-telegraph
https://script.hotjar.com/modules.1eae5f578812029ee612.js$script,important,redirect=sugarcoat-modules.1eae5f578812029ee612 has been made redundant by https://script.hotjar.com/modules.1eae5f578812029ee612.js$script,important,redirect=sugarcoat-modules.1eae5f578812029ee612
https://www.google-analytics.com/analytics.js$script,important,redirect=sugarcoat-analytics_1 has been made redundant by https://www.google-analytics.com/analytics.js$script,important,redirect=sugarcoat-analytics_1
```

**Comment by ryanbr** [comment]
Not sure what the "_1" is, when comparing these similar filters,
`https://www.google-analytics.com/analytics.js$script,important,redirect=sugarcoat-analytics_1` vs `https://www.google-analytics.com/analytics.js$script,important,redirect=sugarcoat-analytics`

**Comment by ShivanKaul** [comment]
Thanks for the review @ryanbr! I added a new commit with the following cleanups:
1. Ran a redundancy check on https://adblockplus.org/redundancy_check
2. Cleaned up the http bits to be `||`

The sugarcoat script was run on a number of different websites individually, hence the duplicates (and hence why sugarcoat-analytics_1 and sugarcoat-analytics are the same script - on a website crawl there might have been 2 scripts named analytics.js that would result in one of them being suffixed with `_1`). I've cleaned up the duplicates manually. 

One q for someone more knowledgeable than me in filter rules: there are a number of rules that look similar to:
`||securepubads.g.doubleclick.net/gpt/pubads_impl_2021072701.js`
for e.g.: 
```
||securepubads.g.doubleclick.net/gpt/pubads_impl_2021072403.js$script,important,redirect=sugarcoat-pubads_impl_2021072403
||securepubads.g.doubleclick.net/gpt/pubads_impl_2021070101.js$script,important,redirect=sugarcoat-pubads_impl_2021070101
```
All these scripts are the same. Should we just have the following rule to catch them all?
`||securepubads.g.doubleclick.net/gpt/pubads_impl_*.js$script,important,redirect=sugarcoat-pubads_impl`

**Comment by ryanbr** [comment]
`||securepubads.g.doubleclick.net/gpt/pubads_impl_$script,important,redirect=sugarcoat-pubads_impl`  (without the need for the wildcard would be enough @ShivanKaul

**Comment by ShivanKaul** [comment]
For the `adobedtm.com launch` suggestions: I don't think they're all the same i.e. https://assets.adobedtm.com/5d4962a43b79/c1061d2c5e7b/launch-191c2462b890.min.js is not the same as https://assets.adobedtm.com/launch-EN3932511771fb4e5e9dd852ae89372b59.min.js which is also not the same as https://assets.adobedtm.com/launch-EN578e54a3f0c6478aa41c89022e30863c.min.js (subtle differences).

**Comment by ryanbr** [comment]
> For the `adobedtm.com launch` suggestions: I don't think they're all the same i.e. https://assets.adobedtm.com/5d4962a43b79/c1061d2c5e7b/launch-191c2462b890.min.js is not the same as https://assets.adobedtm.com/launch-EN3932511771fb4e5e9dd852ae89372b59.min.js which is also not the same as https://assets.adobedtm.com/launch-EN578e54a3f0c6478aa41c89022e30863c.min.js (subtle differences).

Ah okay, was worth a shot to ask. The rest should covered, giving us the best protection

**Comment by ShivanKaul** [comment]
@ryanbr as discussed on DM, I've gone back to the original uncollapsed filters with `domain=` filters added because a sugarcoated resource is specific to that website's usage of the resource. So even though the original resource is is the same, the sugarcoated resource could be different. I've added an MD5 hash of the sugarcoated script's contents to the replacement resource name which would take care of collisions (worth noting that https://adblockplus.org/redundancy_check does not seem to account for domain= differences).

**Comment by ShivanKaul** [comment]
@pes10k just a heads-up that I've added a domain filter option on the rules (which is a change from how sugarcoat was originally written) for the reasons above ^

**Review by ryanbr — APPROVED** [review]
Looks fine now

**Review by antonok-edm — APPROVED** [review]

**Pull request merged**
