### PR TITLE
Fix syndication.twitter.com whitelist to allow Easyprivacy block the Twitter tracker

### PR DESCRIPTION
**Pull request by ryanbr**
Tested on the following sites;

   `https://wet-boew.github.io/v4.0-ci/demos/twitter/twitter-en.html`
   `http://twitframe.com/`
   `https://buffer.com/library/twitter-moments`

Our current whitelist `@@||syndication.twitter.com/$tag=twitter-embeds` Allows the following tracking scripts through:

`https://syndication.twitter.com/i/jot`
`https://syndication.twitter.com/i/jot?l=%7B%22widget_origin%22%3A%22https%3A%2F%2Fwet-boew.github.io%2Fv4.0-ci%2Fdemos%2Ftwitter%2Ftwitter-en.html%22%2C%22widget_frame%22%3Afalse%2C%22widget_data_source%22%3A%22profile%3AWebExpToolkit%22%2C%22query%22%3Anull%2C%22profile_id%22%3Anull%2C%22_category_%22%3A%22tfw_client_event%22%2C%22triggered_on%22%3A1570093351729%2C%22dnt%22%3Afalse%2C%22client_version%22%3A%22708eecd%3A1570046592825%22%2C%22format_version%22%3A%22708eecd%3A1570046592825%22%2C%22event_namespace%22%3A%7B%22client%22%3A%22tfw%22%2C%22page%22%3A%22timeline%22%2C%22element%22%3A%22notice%22%2C%22section%22%3A%22header%22%2C%22action%22%3A%22seen%22%7D%7D&notice_seen=true`
`​https://syndication.twitter.com/i/jot/syndication?l=%7B%22_category_%22%3A%22syndicated_impression%22%2C%22triggered_on%22%3A1570093351087%2C%22dnt%22%3Afalse%2C%22event_namespace%22%3A%7B%22client%22%3A%22tfw%22%2C%22page%22%3A%22timeline%22%2C%22action%22%3A%22impression%22%7D%7D`

We have an existing filter in Easyprivacy `||twitter.com/i/jot` blocking these twitter trackers.

Whitelisting this (xmlhttprequest request) seems fine: `https://syndication.twitter.com/settings` would be more specific and avoid letting the tracking in.

The other option is @@||syndication.twitter.com/settings$tag=twitter-embeds  But kept it generic for safety-sake.

### CODE REVIEW

**Comment by snyderp** [comment]
@bbondy I think you created all the `twitter-embed` entries.  Does this look a-ok to you?

**Comment by bbondy** [comment]
Looks fine to me as long as the embed still continues to work with the change 👍

**Comment by snyderp** [comment]
@ryanbr can you confirm if embeds still work with the change?  if so, i'll merge / approve

**Comment by ryanbr** [comment]
Okay, will re-review these twitter whitelists. I'll need to look at the other social domains also, to see how current these whitelists are.

**Comment by ryanbr** [comment]
2 new filters (Based on the sample domains from the original commit)

`@@||twitter.com/sw.js$tag=twitter-embeds`
`@@||ton.twimg.com^$tag=twitter-embeds`

Cleaned up the other domains.

**Pull request merged**
