### PR TITLE
Fixes for  https://blog.batcommunity.org/

### PR DESCRIPTION
**Pull request by ryanbr**
Looks a little broken due to blocking of reddit.  https://blog.batcommunity.org/2019/07/weeklyupdate-jun28-jul04/

This will be removed once adblock-rust lands. (similar vain to https://github.com/brave/adblock-lists/pull/99)

### CODE REVIEW

**Comment by ryanbr** [comment]
We're also blocking twitter images on https://blog.batcommunity.org/2019/07/weeklyupdate-jun28-jul04/

Lets allow twitter images to be viewed :)

**Comment by snyderp** [comment]
@ryanbr, I'm fine with adding this rule, but only if we can _also_ make sure we're not sending tracking pixel requests out.  Can you customize this rule (or add additional rules) so that 
1) It blocks the URL(s?) twitter uses for its tracking pixels
2) Allows all other third party image requests?

**Comment by ryanbr** [comment]
twimg.com  is used for the images on twitter directly. The twitter trackers urls already taken care of in EP; We could make it generic outright, but I've kept it specific for the time being. 

From; https://blog.batcommunity.org/2019/07/weeklyupdate-jun28-jul04/

`https://abs.twimg.com/emoji/v2/72x72/2611.png`
​`https://abs.twimg.com/emoji/v2/72x72/1f1ef-1f1f2.png `

In Easyprivacy:

`||twitter.com/i/jot`

`https://syndication.twitter.com/i/jot`
`https://syndication.twitter.com/i/jot?dnt=1&l=%7B%22widget_origin%22%3A%22https%3A%2F%2Fblog.batcommunity.org%2F2019%2F07%2Fwe...`
`https://syndication.twitter.com/i/jot/syndication?dnt=1&l=%7B%22_category_%22%3A%22syndicated_impression%22%2C%22triggered_on%2`

**Comment by ryanbr** [comment]
Just a followup, if you visit twitter.com directly. all the "twimg.com" domain items are legit image/video content, basically the same items when they're embedded outside twitter.

**Comment by snyderp** [comment]
This looks good, but it looks like there is now a merge issue.  Can you clean up the PR so that it merges cleanly, and I'll merge right away?

**Comment by ryanbr** [comment]
Ok, I think that did it.

**Pull request merged**
