### PR TITLE
Video playback is broken on https://www.zdnet.com

### PR DESCRIPTION
**Pull request by ryanbr**
Made it domain specific, but it may need to be generic depending on how popular this specific script is.

Filter is blocked via disconnect; this fix's it.

### CODE REVIEW

**Comment by ryanbr** [comment]
Test url;

`https://www.zdnet.com/article/brave-defies-googles-moves-to-cripple-ad-blocking-with-new-69x-faster-rust-engine/`

**Comment by snyderp** [comment]
This is another "the fix enables tracking" fix (might not be any other way), but want to get an official policy set internally before deciding on these.  Blocking for the moment on the #ads-blocking convo

**Comment by BrendanEich** [comment]
@snyderp We have the policy worked out, can you put it in this repo's wiki so we can all refer to it? Thanks.

**Comment by snyderp** [comment]
@BrendanEich done and done
https://github.com/brave/adblock-lists/wiki/Policy-on-Filter-List-Exceptions

**Pull request merged**
