### PR TITLE
Ads on http://www.imkan.tv/ (Chinese)

### PR DESCRIPTION
**Pull request by ryanbr**
Was requested by a user who DM'd us. from the site: `http://www.imkan.tv`

Blocks the following;

`||asset.bixjf.com/2019/tv/20190527/afadad90f0be047648e5cfca78a57fbb.jpg$image`
`||asset.bixjf.com/2019/tv/20190722/120f68fc3b717314b060e1d33f457b33.jpg$image`
`||asset.bixjf.com/2019/tv/20190719/93e7dca4ee88aec344a99ed9771fc36b.jpg$image`
`||asset.bixjf.com/2019/tv/20190802/ad5830247f593226f9f6c7cb7ba901b1.jpg$image`
`||asset.bixjf.com/2019/tv/20190809/9531e7bec10bb1227369ba53f8cbd42b.jpg$image`

### CODE REVIEW

**Comment by snyderp** [comment]
Would it be better to remove the data dependency here?  If its already going to be a full regex match, what about:

`||asset.bixjf.com/[0-9]{4}/tv/*.jpg|$image,domain=imkan.tv`

**Comment by ryanbr** [comment]
Okay, sure regex could work. Here is something (a little more specific

`/^https?:\/\/asset.bixjf.com\/[0-9]{4}\/[a-z]{2,}\/[0-9].*(.jpg$)/$image`

**Comment by snyderp** [comment]
Great!  If this can be domain specific, then i think all good to go!

**Comment by ryanbr** [comment]
All good, just waiting on the user, got another filter that the user is testing out. to hopefully prevent the video ads

**Comment by ryanbr** [comment]
The 2nd regex is covering this filter:

`https://asset.bixjf.com/2019/ad/20190805/6c62d102bbefcd0be512de971234f52b.mp4`

**Pull request merged**
